version: "3"
services:
    mot-history-server:
        build: .
        image: cryptweet-bot:1.0.17
        environment:
            - DISCORD_TOKEN=${DISCORD_TOKEN}
            - TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY}
            - TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET}
            - TWITTER_TOKEN_KEY=${TWITTER_TOKEN_KEY}
            - TWITTER_TOKEN_SECRET=${TWITTER_TOKEN_SECRET}
        ports:
            - '9015:80'
        restart: always
        container_name: cryptweet-bot
